import { ImportStage, ImportStatus, Prisma, type Import, type PrismaClient } from "@prisma/client";
import { IMPORT_MESSAGES } from "../../constants/index.js";
import { NotFoundError } from "../../errors/not-found.error.js";

export interface CreateImportData {
  /** Generated by the caller, because the object key embeds it. */
  id: string;
  projectId: string;
  schemaId: string;
  uploadedById: string;
  filename: string;
  objectKey: string;
  sizeBytes: number;
  contentType: string;
}

export class ImportRepository {
  constructor(private readonly prisma: PrismaClient) {}

  async create(data: CreateImportData): Promise<Import> {
    try {
      return await this.prisma.import.create({
        data: { ...data, sizeBytes: BigInt(data.sizeBytes) },
      });
    } catch (error) {
      throw toDomainError(error);
    }
  }

  async findById(id: string): Promise<Import | null> {
    return this.prisma.import.findUnique({ where: { id } });
  }

  /**
   * UPLOADING -> QUEUED, conditionally.
   *
   * The `status` in the WHERE clause is the whole point: it makes the transition
   * atomic, so two concurrent `start` calls cannot both succeed. The loser sees
   * `count === 0` and is told the import has already been started, rather than a
   * second RabbitMQ message being published for the same import.
   *
   * Same pattern the worker will use to claim a job, and the same reason
   * `SELECT` then `UPDATE` would not do — both readers would see UPLOADING.
   */
  async markQueued(id: string): Promise<boolean> {
    const { count } = await this.prisma.import.updateMany({
      where: { id, status: ImportStatus.UPLOADING },
      data: { status: ImportStatus.QUEUED, queuedAt: new Date() },
    });
    return count === 1;
  }

  /**
   * Undo markQueued when publishing the job failed.
   *
   * Without this, a broker outage between the UPDATE and the publish would
   * leave the row at QUEUED with no message in existence — permanently stuck,
   * because `start()` refuses to run again on a non-UPLOADING import. Reverting
   * makes the whole operation retryable.
   */
  async revertToUploading(id: string): Promise<void> {
    await this.prisma.import.updateMany({
      where: { id, status: ImportStatus.QUEUED },
      data: { status: ImportStatus.UPLOADING, queuedAt: null },
    });
  }

  /**
   * QUEUED -> PROCESSING, conditionally. The worker's claim.
   *
   * RabbitMQ guarantees at-least-once delivery, so the same message WILL
   * sometimes arrive twice (a redelivery after a worker died, for instance).
   * Returning false here means someone else owns this import, or it was
   * cancelled while queued — either way the delivery should be acked and
   * dropped rather than processed.
   *
   * Must be a conditional UPDATE, not SELECT-then-UPDATE: two workers reading
   * the status simultaneously would both see QUEUED and both proceed.
   */
  async claimForProcessing(id: string): Promise<boolean> {
    const { count } = await this.prisma.import.updateMany({
      where: { id, status: ImportStatus.QUEUED },
      data: {
        status: ImportStatus.PROCESSING,
        stage: ImportStage.FILE_VALIDATION,
        startedAt: new Date(),
      },
    });
    return count === 1;
  }
}

function toDomainError(error: unknown): unknown {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    // P2003 = foreign key violation: the project, schema or uploader is gone.
    if (error.code === "P2003") {
      return new NotFoundError(IMPORT_MESSAGES.NOT_FOUND);
    }
    // P2025 = the row to update doesn't exist.
    if (error.code === "P2025") {
      return new NotFoundError(IMPORT_MESSAGES.NOT_FOUND);
    }
  }
  return error;
}
