/**
 * Object key layout. These live here rather than inline because the API writes
 * keys and the worker reads them — if the two ever disagree the worker looks
 * for a file that doesn't exist, with no compile error to warn you.
 *
 *   project-<projectId>/import-<importId>/original.csv
 *   project-<projectId>/import-<importId>/error-report.csv
 *
 * S3 has no directories. The slashes are just characters in the key, which is
 * why "delete this import" is a delete-by-prefix rather than an rmdir.
 */
export const STORAGE_KEYS = {
  /** The uploaded file. Never uses the user's filename — see IMPORT_FILE_BASENAME. */
  importOriginal: (projectId: string, importId: string, extension: string): string =>
    `${STORAGE_KEYS.importPrefix(projectId, importId)}original.${extension}`,

  /** Generated by the worker. Overwritten on retry. */
  importErrorReport: (projectId: string, importId: string): string =>
    `${STORAGE_KEYS.importPrefix(projectId, importId)}error-report.csv`,

  /** Everything belonging to one import — used to clean up after a delete. */
  importPrefix: (projectId: string, importId: string): string =>
    `project-${projectId}/import-${importId}/`,

  /** Everything belonging to one project. */
  projectPrefix: (projectId: string): string => `project-${projectId}/`,
} as const;

/**
 * Upload formats we accept. JSON lands on Day 4 — it needs a second streaming
 * parser (stream-json), not just a MIME type added here.
 *
 * The stored key's extension comes from this allow-list, never from the user's
 * filename: an attacker-controlled filename in an object key means path
 * traversal, unicode surprises and length-limit problems.
 */
export const ALLOWED_IMPORT_EXTENSIONS = ["csv"] as const;

export type AllowedImportExtension = (typeof ALLOWED_IMPORT_EXTENSIONS)[number];

/** Content types accepted for each extension. Browsers are inconsistent here. */
export const ALLOWED_IMPORT_CONTENT_TYPES: Record<AllowedImportExtension, readonly string[]> = {
  csv: ["text/csv", "application/csv", "application/vnd.ms-excel", "text/plain"],
} as const;

/** S3's DeleteObjects accepts at most 1000 keys per call. */
export const S3_DELETE_BATCH_SIZE = 1000;

/** How much of a file the preview endpoint reads. One ranged GET, never the whole object. */
export const PREVIEW_BYTE_RANGE = 64 * 1024;
